# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-06 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.CharField(max_length=128)),
                ('file_format', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.CharField(max_length=32)),
                ('participant', models.CharField(max_length=32)),
                ('story', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('twitter_id', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cover', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='works.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Work'),
        ),
    ]
